OBJS =		IsProcessExist.o
TARGET =	../../web-control-center/usr/bin/web-control-center/IsProcessExist

$(TARGET):	$(OBJS)
	$(CXX) -o $(TARGET) $(OBJS) $(LIBS)

all:	$(TARGET)

clean:
	rm -f $(OBJS) $(TARGET)
